package com.gafipro.minigames.game.puzzle;

import com.gafipro.minigames.game.BaseGame;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.DrawContext;
import org.lwjgl.glfw.GLFW;

import java.util.ArrayList;
import java.util.List;

/** Solvable sliding-tile puzzle generated by legal moves only. */
public final class SlidingPuzzleGame extends BaseGame {
    private int size = 4;
    private int[] board;
    private int empty;

    @Override public String id() { return "sliding_puzzle"; }
    @Override public String title() { return "Sliding Puzzle"; }
    @Override public String category() { return "Puzzle"; }

    @Override public void start() {
        board = new int[size * size];
        for (int i = 0; i < board.length; i++) board[i] = i;
        empty = board.length - 1;
        int previous = -1;
        for (int i = 0; i < 500; i++) {
            List<Integer> choices = neighbors(empty);
            choices.remove((Integer) previous);
            int next = choices.get(random.nextInt(choices.size()));
            swap(empty, next);
            previous = empty;
            empty = next;
        }
        if (solved()) {
            int next = neighbors(empty).get(0);
            swap(empty, next);
            empty = next;
        }
        status = "Click a tile next to the empty space • R restart • 3/4/5 changes size";
    }

    private List<Integer> neighbors(int index) {
        List<Integer> result = new ArrayList<>(4);
        int x = index % size, y = index / size;
        if (x > 0) result.add(index - 1);
        if (x + 1 < size) result.add(index + 1);
        if (y > 0) result.add(index - size);
        if (y + 1 < size) result.add(index + size);
        return result;
    }

    private void swap(int a, int b) { int t = board[a]; board[a] = board[b]; board[b] = t; }
    private boolean solved() { for (int i = 0; i < board.length; i++) if (board[i] != i) return false; return true; }

    @Override public boolean mouseClicked(double mx, double my, int button) {
        if (button != 0 || finished) return true;
        int cell = Math.min(58, Math.max(30, (MinecraftClient.getInstance().getWindow().getScaledHeight() - 145) / size));
        int ox = cx() - size * cell / 2, oy = 80;
        int x = (int) ((mx - ox) / cell), y = (int) ((my - oy) / cell);
        if (x < 0 || y < 0 || x >= size || y >= size) return true;
        int index = y * size + x;
        if (!neighbors(empty).contains(index)) return true;
        swap(empty, index);
        empty = index;
        markMove();
        status = "Moves: " + metrics.moves() + " • Click a neighboring tile";
        if (solved()) finishWin(Math.max(100, 10000 - metrics.moves() * 12));
        return true;
    }

    @Override public void render(DrawContext c, int mx, int my, float delta) {
        MinecraftClient mc = MinecraftClient.getInstance();
        drawHeader(c, "SLIDING PUZZLE", status);
        int cell = Math.min(58, Math.max(30, (mc.getWindow().getScaledHeight() - 145) / size));
        int ox = cx() - size * cell / 2, oy = 80;
        for (int i = 0; i < board.length; i++) {
            int x = ox + i % size * cell, y = oy + i / size * cell;
            int value = board[i];
            c.fill(x + 1, y + 1, x + cell - 2, y + cell - 2, value == board.length - 1 ? 0xFF30363D : 0xFF4B6A88);
            if (value != board.length - 1) c.drawCenteredTextWithShadow(mc.textRenderer, net.minecraft.text.Text.literal(Integer.toString(value + 1)), x + cell / 2, y + cell / 2 - 5, 0xFFFFFFFF);
        }
    }

    @Override public void keyPressed(int key, int scan, int modifiers) {
        if (key == GLFW.GLFW_KEY_R) begin();
        else if (key == GLFW.GLFW_KEY_3 || key == GLFW.GLFW_KEY_4 || key == GLFW.GLFW_KEY_5) {
            size = key == GLFW.GLFW_KEY_3 ? 3 : key == GLFW.GLFW_KEY_4 ? 4 : 5;
            begin();
        }
    }
}
